on: pull_request

jobs:
  test:
    # TODO switch to wine/proton
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure
        run: cmake -S . -B build -DENABLE_TESTS=ON -A x64
      - name: Build
        run: cmake --build build -A x64
      - name: Run tests
        run: ctest --test-dir build
